Repository Eroar/Ludum-Dare-46, pull requests merged in 2020-04, with the labels that each got.

#19 Moving Platforms
  Assets/Packages.meta
  Assets/Packages/RestSharp.106.10.1.meta
  Assets/Packages/RestSharp.106.10.1/lib.meta
  Assets/Prefabs/Platform.prefab
  Assets/Prefabs/Platform.prefab.meta
  Assets/Scenes/lvl_1.unity
  Assets/Scripts/Activatable.cs
  Assets/Scripts/Activatable.cs.meta
  Assets/Scripts/Player.cs
  Assets/Scripts/logic.meta
  Assets/Scripts/logic/logicGate.cs
  Assets/Scripts/logic/logicGate.cs.meta
  Assets/Scripts/logic/logicInput.cs
  Assets/Scripts/logic/logicInput.cs.meta
  Assets/Scripts/logic/logicLever.cs
  Assets/Scripts/logic/logicLever.cs.meta
  Assets/Scripts/logic/logicPressurePlate.cs
  Assets/Scripts/logic/logicPressurePlate.cs.meta
  Assets/Scripts/moving_platform.cs
  Assets/Scripts/moving_platform.cs.meta
Labels: ERYK ZMERGÓJ MNIE, enhancement

#41 Leaderboard pls work
  .gitignore
  Assets/NuGet.config
  Assets/NuGet.config.meta
  Assets/NuGet.meta
  Assets/NuGet/Editor.meta
  Assets/NuGet/Editor/DotNetZip.dll
  Assets/NuGet/Editor/DotNetZip.dll.meta
  Assets/NuGet/Editor/NugetForUnity.dll
  Assets/NuGet/Editor/NugetForUnity.dll.meta
  Assets/NuGet/LICENSE
  Assets/NuGet/LICENSE.meta
  Assets/NuGet/README.pdf
  Assets/NuGet/README.pdf.meta
  Assets/NuGet/Resources.meta
  Assets/NuGet/Resources/defaultIcon.png
  Assets/NuGet/Resources/defaultIcon.png.meta
  Assets/Packages.meta~HEAD
  Assets/Packages.meta~HEAD.meta
  Assets/Packages.meta~grzesStuff1
  Assets/Packages.meta~grzesStuff1.meta
  Assets/Packages/RestSharp.106.10.1.meta~HEAD
  Assets/Packages/RestSharp.106.10.1.meta~HEAD.meta
  Assets/Packages/RestSharp.106.10.1.meta~grzesStuff1
  Assets/Packages/RestSharp.106.10.1.meta~grzesStuff1.meta
  Assets/Packages/RestSharp.106.10.1/.signature.p7s
  Assets/Packages/RestSharp.106.10.1/RestSharp.106.10.1.nupkg
  Assets/Packages/RestSharp.106.10.1/RestSharp.106.10.1.nupkg.meta
  Assets/Packages/RestSharp.106.10.1/RestSharp.106.10.1.nupkg.meta~HEAD
  Assets/Packages/RestSharp.106.10.1/RestSharp.106.10.1.nupkg.meta~HEAD.meta
  Assets/Packages/RestSharp.106.10.1/RestSharp.106.10.1.nupkg.meta~grzesStuff1
  Assets/Packages/RestSharp.106.10.1/RestSharp.106.10.1.nupkg.meta~grzesStuff1.meta
  Assets/Packages/RestSharp.106.10.1/lib.meta
  Assets/Scenes/LeaderboardTesting.unity
  Assets/Scenes/LeaderboardTesting.unity.meta
  Assets/Scripts/LeaderBoardHandler.cs
  Assets/Scripts/LeaderBoardHandler.cs.meta
  Assets/Scripts/LeaderBoardHandler.cs.meta~HEAD
  Assets/Scripts/LeaderBoardHandler.cs.meta~HEAD.meta
  Assets/Scripts/LeaderBoardHandler.cs.meta~grzesStuff1
  Assets/Scripts/LeaderBoardHandler.cs.meta~grzesStuff1.meta
  Assets/Scripts/tests.meta
  Assets/Scripts/tests/LeaderboardTest.cs
  Assets/Scripts/tests/LeaderboardTest.cs.meta
  Assets/Scripts/tests/LeaderboardTest.cs.meta~HEAD
  Assets/Scripts/tests/LeaderboardTest.cs.meta~HEAD.meta
  Assets/Scripts/tests/LeaderboardTest.cs.meta~grzesStuff1
  Assets/Scripts/tests/LeaderboardTest.cs.meta~grzesStuff1.meta
  Assets/packages.config
  Assets/packages.config.meta
  Leaderboard/app/routes.py
  Leaderboard/app/static/main.css
  Leaderboard/app/templates/board.html
  Leaderboard/app/templates/index.html
  Leaderboard/test.json
Labels: ERYK ZMERGÓJ MNIE, FREE CODE NO SCAM 100% LEGIT, Just merge it!, No conflicts; easy merge, You can just force push master, bug, documentation, duplicate, enhancement, good first issue, help wanted, https://youtu.be/dQw4w9WgXcQ, invalid, merge into me senpai, question, wontfix

#42 Vanishing Block
  Assets/Prefabs/ActiveBlock1.prefab
  Assets/Prefabs/ActiveBlock1.prefab.meta
  Assets/Prefabs/logicGate.prefab
  Assets/Scenes/lvl_1.unity
  Assets/Scripts/ActiveBlock1.cs
  Assets/Scripts/ActiveBlock1.cs.meta
Labels: FREE CODE NO SCAM 100% LEGIT, enhancement

#43 Baby Drop
  Assets/Scripts/Damaging.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/UI_Handler.cs
Labels: ERYK ZMERGÓJ MNIE, FREE CODE NO SCAM 100% LEGIT, You can just force push master

#8 Create README.md
  README.md
Labels: ERYK ZMERGÓJ MNIE, documentation, enhancement, good first issue, help wanted
